version: '3.8'

services:
 mysql:
  image: mysql:8.0.32
  container_name: mysql-container
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: mypassword
   MYSQL_DATABASE: challenge
   MYSQL_USER: myuser
   MYSQL_PASSWORD: mypassword
  ports:
   - '3306:3306'
  volumes:
   - ./data/mysql_data:/var/lib/mysql
